### ISSUE TITLE
version not consistent

### ISSUE THREAD

**Issue by wmoebius** [conda-forge/scikit-fmm-feedstock#11]
Problem with versions of scikit-fmm on conda-forge:

The instructions imply that 2021.2.2 is installed with both `conda install -c conda-forge scikit-fmm` and `conda install -c conda-forge/label/cf202003 scikit-fmm`.

The latter installs the older version 2019.1.30, which is the version corresponding to the label, but unexpected behavior.

**Comment by jan-janssen** [comment]
The latter version is the python 2.7 compatible version. Python 2.7 was depreciated early last year https://conda-forge.org/docs/user/announcements.html#id1

**Comment by wmoebius** [comment]
Ah, great. I naively assumed that the label would refer to the latest version, I understand now.
